### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by stuartaccent** [AccentDesign/wagtailcolourpicker#1]
- [x] Make sure only colours can be added not random guff
- [ ] See if we can avoid overriding the RickTextBlock for the cached property
- [x] Remove the add new colour field in the form via a setting. So that colours can be fixed per site
- [x] Add picker urls via cms hook

**Comment by craigvincent** [comment]
RickTextBlock? 😉 

![image](https://media.giphy.com/media/zSZphHD724VUI/giphy.gif)

**Comment by stuartaccent** [comment]
lol

**Comment by adamhalesworth** [comment]
`!_you.Give(up);`
